# Analisi sul dataset Ecommerce Order & Supply Chain Dataset
Il <a href="https://www.kaggle.com/datasets/bytadit/ecommerce-order-dataset">dataset **Ecommerce Order & Supply Chain Dataset**</a> su Kaggle
- Contenuto: informazioni su ordini, righe d’ordine (items), clienti, prodotti, pagamenti e aspetti di supply chain.
- Dimensione: il dataset contiene migliaia di record complessivi (oltre 5.000 righe), sufficienti per analisi statistiche significative.

In [47]:
# import library
# data analisys
import pandas as pd 
import numpy as np 
# data visualization
import seaborn as sns
import matplotlib.pyplot as plt 
from matplotlib.dates import DateFormatter, AutoDateLocator
print(pd.__version__, np.__version__, sns.__version__)

2.3.3 2.3.5 0.13.2

## Comprensione dei Dati (EDA)

In [48]:
# Import dataset or dataframe / Importo set di dati o dataframe
dfcustomers = pd.read_csv('df_Customers.csv', low_memory=False)

# Leggo le prime 4 righe del dataframe e le visualizzo nello schermo
display(dfcustomers.head(4))

    customer_id  customer_zip_code_prefix       customer_city customer_state
0  hCT0x9JiGXBQ                     58125     varzea paulista             SP
1  PxA7fv9spyhx                      3112  armacao dos buzios             RJ
2  g3nXeJkGI0Qw                      4119             jandira             SP
3  EOEsCQ6QlpIg                     18212          uberlandia             MG

In [49]:
# Import dataset or dataframe / Importo set di dati o dataframe
dfproducts = pd.read_csv('df_Products.csv', low_memory=False)

# Leggo le prime 4 righe del dataframe e le visualizzo nello schermo
display(dfproducts.head(4))

,product_id,product_category_name,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,90K0C1fIyQUf,toys,491.0,19.0,12.0,16.0
1,qejhpMGGVcsl,watches_gifts,440.0,18.0,14.0,17.0
2,qUS5d2pEAyxJ,costruction_tools_garden,2200.0,16.0,16.0,16.0
3,639iGvMyv0De,toys,1450.0,68.0,3.0,48.0

In [50]:
# Import dataset or dataframe / Importo set di dati o dataframe
dforders = pd.read_csv('df_Orders.csv', low_memory=False)

# Leggo le prime 4 righe del dataframe e le visualizzo nello schermo
display(dforders.head(4))

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_timestamp,order_estimated_delivery_date
0,Axfy13Hk4PIk,hCT0x9JiGXBQ,delivered,10/22/2017 18:57,10/22/2017 19:14,10/26/2017 22:19,11/9/2017
1,v6px92oS8cLG,PxA7fv9spyhx,delivered,6/20/2018 21:40,6/20/2018 22:20,7/3/2018 22:51,7/24/2018
2,Ulpf9skrhjfm,g3nXeJkGI0Qw,delivered,2/16/2018 16:19,2/17/2018 16:15,2/27/2018 1:29,3/8/2018
3,bwJVWupf2keN,EOEsCQ6QlpIg,delivered,8/18/2018 18:04,8/18/2018 18:15,8/27/2018 20:03,9/19/2018

In [51]:
# Import dataset or dataframe / Importo set di dati o dataframe
dforder_items = pd.read_csv('df_OrderItems.csv', low_memory=False)

# Leggo le prime 4 righe del dataframe e le visualizzo nello schermo
display(dforder_items.head(4))

       order_id    product_id     seller_id   price  shipping_charges
0  Axfy13Hk4PIk  90K0C1fIyQUf  ZWM05J9LcBSF  223.51             84.65
1  v6px92oS8cLG  qejhpMGGVcsl  IjlpYfhUbRQs  170.80             23.79
2  Ulpf9skrhjfm  qUS5d2pEAyxJ  77p2EYxcM9MD   64.40             17.38
3  bwJVWupf2keN  639iGvMyv0De  jWzS0ayv9TGf  264.50             30.72

In [52]:
# Import dataset or dataframe / Importo set di dati o dataframe
dfpayments = pd.read_csv('df_Payments.csv', low_memory=False)

# Leggo le prime 4 righe del dataframe e le visualizzo nello schermo
display(dfpayments.head(4))

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,Axfy13Hk4PIk,1,credit_card,1,259.14
1,v6px92oS8cLG,1,credit_card,8,382.39
2,Ulpf9skrhjfm,1,credit_card,4,249.25
3,bwJVWupf2keN,1,credit_card,2,27.79

### Shape e Struttura base
<i>Obiettivo: capire volume e tipi dati.</i>

- 1. Il **dataframe CUSTOMERS** in analisi ha 89316 righe e 4 colonne.
- 2. Il **dataframe PRODUCTS** in analisi ha 89316 righe e 6 colonne.
- 3. Il **dataframe ORDERS** in analisi ha 89316 righe e 7 colonne.
- 4. Il **dataframe ORDER ITEMS** in analisi ha 89316 righe e 5 colonne.
- 5. Il **dataframe PAYMENTS** in analisi ha 89316 righe e 5 colonne.

In [55]:
# Mostro il numero di righe e il numero di colonne
display('Numero di righe e colonne', dfcustomers.shape)
# Mostro tutti nomi delle colonne del dataframe
display('Nome delle colonne',dfcustomers.columns)
# Mostro le distribuzione del tipo valore
display(dfcustomers.dtypes.value_counts())

'Numero di righe e colonne'

(89316, 4)

'Nome delle colonne'

Index(['customer_id', 'customer_zip_code_prefix', 'customer_city',
       'customer_state'],
      dtype='object')

object    3
int64     1
Name: count, dtype: int64

In [56]:
# Mostro il numero di righe e il numero di colonne
display('Numero di righe e colonne', dfproducts.shape)
# Mostro tutti nomi delle colonne del dataframe
display('Nome delle colonne',dfproducts.columns)
# Mostro le distribuzione del tipo valore
display(dfproducts.dtypes.value_counts())

'Numero di righe e colonne'

(89316, 6)

'Nome delle colonne'

Index(['product_id', 'product_category_name', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm'],
      dtype='object')

float64    4
object     2
Name: count, dtype: int64

In [57]:
# Mostro il numero di righe e il numero di colonne
display('Numero di righe e colonne', dforders.shape)
# Mostro tutti nomi delle colonne del dataframe
display('Nome delle colonne',dforders.columns)
# Mostro le distribuzione del tipo valore
display(dforders.dtypes.value_counts())

'Numero di righe e colonne'

(89316, 7)

'Nome delle colonne'

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_timestamp',
       'order_estimated_delivery_date'],
      dtype='object')

object    7
Name: count, dtype: int64

In [58]:
# Mostro  il numero di righe e il numero di colonne
display('Numero di righe e colonne', dforder_items.shape)
# Mostro  tutti nomi delle colonne del dataframe
display('Nome delle colonne',dforder_items.columns)
# Mostro  le distribuzione del tipo valore
display(dforder_items.dtypes.value_counts())

'Numero di righe e colonne'

(89316, 5)

'Nome delle colonne'

Index(['order_id', 'product_id', 'seller_id', 'price', 'shipping_charges'], dtype='object')

object     3
float64    2
Name: count, dtype: int64

In [59]:
# Mostro  il numero di righe e il numero di colonne
display('Numero di righe e colonne', dfpayments.shape)
# Mostro  tutti nomi delle colonne del dataframe
display('Nome delle colonne',dfpayments.columns)
# Mostro  le distribuzione del tipo valore
display(dfpayments.dtypes.value_counts())

'Numero di righe e colonne'

(89316, 5)

'Nome delle colonne'

Index(['order_id', 'payment_sequential', 'payment_type',
       'payment_installments', 'payment_value'],
      dtype='object')

object     2
int64      2
float64    1
Name: count, dtype: int64

### Statistiche Descrittive
<i>Obiettivo: capire le colonne e gli attributi presenti nel DataFrame customers, products, orders, order items e payments.</i>

#### 1. Il dataframe CUSTOMERS in analisi ha 89316 righe e 4 colonne.

Dall'analisi descrittiva, posso concludere che non ci sono celle nulle. Non ci sono valori mancanti in nessuna colonna, i tipi di dati sono corretti, che significa che non c'è nulla da pulire nel dataframe del cliente.

Senza valori duplicati.

Le colonne del dataframe Customers nel dettaglio:
- **customer_id**: è un oggetto che contiene l'ID del cliente
- **customer_zip_code_prefix**: è un intero e contiene il codice postale del cliente
- **customer_city**: è un oggetto che contiene la città del cliente
- **customer_state**: è un oggetto che che contiene lo stato dei clienti

Colonne richieste per la tabella `customers`
- `customer_id` (PK)
- `customer_zip_code`
- `customer_city`
- `customer_state`
- `customer_country`

#### Dopo il controllo:
- Trasformato la tabella in base alle entità e agli attributi richiesti con totale di 89316 righe e 5 colonne.

In [60]:
# Import dataset or dataframe / Importo set di dati o dataframe 
dfcustomers = pd.read_csv('df_Customers.csv', low_memory=False)

# Mostrare i nomi delle colonne e i tipi di dati all'interno e se questi dati hanno dei dati mancati
display(dfcustomers.info())
# Genere un riepilogo statistico automatico delle colonne numeriche - Restituisce una tabella con metriche chiave: count (numero valori non-null), mean (media), std (deviazione standard), min (minimo), 25% (1° quartile), 50% (mediana), 75% (3° quartile), max (massimo), evidenziando distribuzioni, outlier e tendenze
display(dfcustomers.describe())
# Genere statistiche descrittive per tutte le colonne del DataFrame, inclusi tipi numerici, categorici (object/string), booleani e datetime, anziché solo numeriche. Per colonne numeriche mostra count, mean, std, min, quartili (25%, 50%/mediana, 75%), max; per categoriche aggiunge unique (valori unici), top (valore più frequente), freq (frequenza top). Esclude NaN automaticamente.
display(dfcustomers.describe(include='all'))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89316 entries, 0 to 89315
Data columns (total 4 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               89316 non-null  object
 1   customer_zip_code_prefix  89316 non-null  int64
 2   customer_city             89316 non-null  object
 3   customer_state            89316 non-null  object
dtypes: int64(1), object(3)
memory usage: 2.7+ MB

None

       customer_zip_code_prefix
count              89316.000000
mean               40499.471080
std                31194.386361
min                 1003.000000
25%                 9785.000000
50%                35480.000000
75%                70040.000000
max                99990.000000

         customer_id  customer_zip_code_prefix customer_city customer_state
count          89316              89316.000000         89316          89316
unique         89316                       NaN          3735             27
top     hCT0x9JiGXBQ                       NaN     sao paulo             SP
freq               1                       NaN         14352          37879
mean             NaN              40499.471080           NaN            NaN
std              NaN              31194.386361           NaN            NaN
min              NaN               1003.000000           NaN            NaN
25%              NaN               9785.000000           NaN            NaN
50%              NaN              35480.000000           NaN            NaN
75%              NaN              70040.000000           NaN            NaN
max              NaN              99990.000000           NaN            NaN

#### 2. Il dataframe PRODUCTS in analisi ha 89316 righe e 6 colonne.

Dall'analisi descrittiva posso concludere che abbiamo 4 parametri a cui mancano la stessa quantità di dati pari a 15, nello specifico: product_weight_g, product_length_cm, product_height_cm, product_width_cm. Invece nella colonna product_category_name la mancanza dei dati è gravemente elevata, ovvero 308 valori mancanti.

Ci sono 61865 righe duplicati × 6 colonne

Le colonne del dataframe Products nel dettaglio:
- **product_id**: è un oggetto che contiene l'ID del prodotto
- **product_category_name**: è un oggetto che contiene il nome della categoria del prodotto
- **product_weight_g**: è un float che contiene il peso del prodotto in grammi
- **product_length_cm**: è un float che contiene la lunghezza del prodotto in cm
- **product_height_cm**: è un float che contiene l'altezza del prodotto in cm
- **product_width_cm**: è un float che contiene la larghezza del prodotto in cm

Colonne richieste per la tabella `products`
- `product_id` (PK)
- `product_category`
- `product_weight_g`
- `product_length_cm`
- `product_height_cm`
- `product_width_cm`

##### Dopo la pulizia:
- Trasformato la tabella in base alle entità e agli attributi richiesti con totale 27308 righe e 6 colonne.

In [61]:
# Import dataset or dataframe / Importo set di dati o dataframe 
dfproducts = pd.read_csv('df_Products.csv', low_memory=False)

# Mostrare i nomi delle colonne e i tipi di dati all'interno e se questi dati hanno dei dati mancati
display(dfproducts.info())
# Genera un riepilogo statistico automatico delle colonne numeriche - Restituisce una tabella con metriche chiave: count (numero valori non-null), mean (media), std (deviazione standard), min (minimo), 25% (1° quartile), 50% (mediana), 75% (3° quartile), max (massimo), evidenziando distribuzioni, outlier e tendenze
display(dfproducts.describe())
# Genera statistiche descrittive per tutte le colonne del DataFrame, inclusi tipi numerici, categorici (object/string), booleani e datetime, anziché solo numeriche. Per colonne numeriche mostra count, mean, std, min, quartili (25%, 50%/mediana, 75%), max; per categoriche aggiunge unique (valori unici), top (valore più frequente), freq (frequenza top). Esclude NaN automaticamente.
display(dfproducts.describe(include='all'))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89316 entries, 0 to 89315
Data columns (total 6 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   product_id             89316 non-null  object
 1   product_category_name  89008 non-null  object
 2   product_weight_g       89301 non-null  float64
 3   product_length_cm      89301 non-null  float64
 4   product_height_cm      89301 non-null  float64
 5   product_width_cm       89301 non-null  float64
dtypes: float64(4), object(2)
memory usage: 4.1+ MB

None

,product_weight_g,product_length_cm,product_height_cm,product_width_cm
count,89301.000000,89301.000000,89301.000000,89301.00000
mean,2087.068129,30.220658,16.559423,23.03421
std,3747.039215,16.110199,13.388514,11.68828
min,0.000000,7.000000,2.000000,6.00000
25%,300.000000,18.000000,8.000000,15.00000
50%,700.000000,25.000000,13.000000,20.00000
75%,1800.000000,38.000000,20.000000,30.00000
max,40425.000000,105.000000,105.000000,118.00000

,product_id,product_category_name,product_weight_g,product_length_cm,product_height_cm,product_width_cm
count,89316,89008,89301.000000,89301.000000,89301.000000,89301.00000
unique,27451,70,NaN,NaN,NaN,NaN
top,0vbEvli2JYJu,toys,NaN,NaN,NaN,NaN
freq,405,67027,NaN,NaN,NaN,NaN
mean,NaN,NaN,2087.068129,30.220658,16.559423,23.03421
std,NaN,NaN,3747.039215,16.110199,13.388514,11.68828
min,NaN,NaN,0.000000,7.000000,2.000000,6.00000
25%,NaN,NaN,300.000000,18.000000,8.000000,15.00000
50%,NaN,NaN,700.000000,25.000000,13.000000,20.00000
75%,NaN,NaN,1800.000000,38.000000,20.000000,30.00000
max,NaN,NaN,40425.000000,105.000000,105.000000,118.00000

#### 3. Il dataframe ORDERS in analisi ha 89316 righe e 7 colonne.

Dall'analisi descrittiva posso concludere che abbiamo 2 parametri a cui mancano dei dati. L'order_delivered_timestamp ha 1889 valori mancanti e la colonna order_approved_at ha 9 valori mancanti.
- order_delivered_timestamp ha 1889 valori mancanti gli stati sono  approved, canceled, invoiced, in processing, shipped and unavailable.

Senza valori duplicati.

Le colonne del dataframe Orders nel dettaglio:
- **order_id**: è un oggetto che contiene l'ID dell'ordine
- **customer_id**: è un oggetto che contiene l'ID del cliente
- **order_status**: è un oggetto che contiene lo stato dell'ordine
- **order_purchase_timestamp**: è un oggetto che contiene contiene la data e l'ora dell'acquisto
- **order_approved_at**: è un oggetto che contiene la data e l'ora in cui l'ordine è stato approvato
- **order_delivered_timestamp**: è un oggetto che contiene la data e l'ora in cui l'ordine è stato spedito per la consegna
- **order_estimated_delivery_date**: è un oggetto che contiene la data stimata di arrivo dell'ordine al cliente

Queste 4 colonne devono essere convertite nel formato date time: order_purchase_timestamp, order_approved_at, order_delivered_timestamp, order_estimated_delivery_date

Colonne richieste per la tabella `orders`
- `order_id` (PK)
- `customer_id` (FK → `customers.customer_id`)
- `order_status`
- `order_date`
- `order_approved_at`
- `delivery_date`
- `estimated_delivery_date`
- `shipping_city`
- `shipping_state`

##### Dopo la pulizia abbiamo 89316 righe e 7 colonne, ho sostituito i valori mancanti la data con datetime predefinito e convertito nel tipo di dati corretto
- Trasformato la tabella in base alle entità e agli attributi richiesti con totale 89316 righe e 9 colonne.

In [62]:
# Import dataset or dataframe / Importo set di dati o dataframe 
dforders = pd.read_csv('df_Orders.csv', low_memory=False)

# Mostrare i nomi delle colonne e i tipi di dati all'interno e se questi dati hanno dei dati mancati
display(dforders.info())
# Genere un riepilogo statistico automatico delle colonne numeriche - Restituisce una tabella con metriche chiave: count (numero valori non-null), mean (media), std (deviazione standard), min (minimo), 25% (1° quartile), 50% (mediana), 75% (3° quartile), max (massimo), evidenziando distribuzioni, outlier e tendenze
display(dforders.describe())
# Genere statistiche descrittive per tutte le colonne del DataFrame, inclusi tipi numerici, categorici (object/string), booleani e datetime, anziché solo numeriche. Per colonne numeriche mostra count, mean, std, min, quartili (25%, 50%/mediana, 75%), max; per categoriche aggiunge unique (valori unici), top (valore più frequente), freq (frequenza top). Esclude NaN automaticamente.
display(dforders.describe(include='all'))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89316 entries, 0 to 89315
Data columns (total 7 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       89316 non-null  object
 1   customer_id                    89316 non-null  object
 2   order_status                   89316 non-null  object
 3   order_purchase_timestamp       89316 non-null  object
 4   order_approved_at              89307 non-null  object
 5   order_delivered_timestamp      87427 non-null  object
 6   order_estimated_delivery_date  89316 non-null  object
dtypes: object(7)
memory usage: 4.8+ MB

None

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_timestamp,order_estimated_delivery_date
count,89316,89316,89316,89316,89307,87427,89316
unique,89316,89316,7,66964,41538,59405,444
top,Axfy13Hk4PIk,hCT0x9JiGXBQ,delivered,8/8/2017 20:26,1/10/2018 10:32,8/14/2017 12:46,12/20/2017
freq,1,1,87428,87,92,87,500

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_timestamp,order_estimated_delivery_date
count,89316,89316,89316,89316,89307,87427,89316
unique,89316,89316,7,66964,41538,59405,444
top,Axfy13Hk4PIk,hCT0x9JiGXBQ,delivered,8/8/2017 20:26,1/10/2018 10:32,8/14/2017 12:46,12/20/2017
freq,1,1,87428,87,92,87,500

#### 4. Il dataframe ORDER ITEMS in analisi ha 89316 righe e 5 colonne.

Dall'analisi descrittiva nessuna colonna contiene valori nulli.

Senza valori duplicati.

Le colonne del dataframe Order Items nel dettaglio:
- **order_id**: è un oggetto che contiene l'ID dell'ordine
- **product_id**: è un oggetto che contiene l'ID del prodotto
- **seller_id**: è un oggetto che contiene l'ID del venditore
- **price**: è un float che contiene il prezzo dell'ordine
- **shipping_charges**: è un float che contiene le spese di spedizione

Colonne richieste per la tabella `order_items`
- `order_item_id` (PK)
- `order_id` (FK → `orders.order_id`)
- `product_id` (FK → `products.product_id`)
- `seller_id`
- `price`
- `shipping_charges`

#### Dopo il controllo:
- Trasformato la tabella in base alle entità e agli attributi richiesti con totale 89316 righe e 6 colonne.

In [63]:
# Import dataset or dataframe / Importo set di dati o dataframe 
dforder_items = pd.read_csv('df_OrderItems.csv', low_memory=False)

# Mostrare i nomi delle colonne e i tipi di dati all'interno e se questi dati hanno dei dati mancati
display(dforder_items.info())
# Genere un riepilogo statistico automatico delle colonne numeriche - Restituisce una tabella con metriche chiave: count (numero valori non-null), mean (media), std (deviazione standard), min (minimo), 25% (1° quartile), 50% (mediana), 75% (3° quartile), max (massimo), evidenziando distribuzioni, outlier e tendenze
display(dforder_items.describe())
# Genere statistiche descrittive per tutte le colonne del DataFrame, inclusi tipi numerici, categorici (object/string), booleani e datetime, anziché solo numeriche. Per colonne numeriche mostra count, mean, std, min, quartili (25%, 50%/mediana, 75%), max; per categoriche aggiunge unique (valori unici), top (valore più frequente), freq (frequenza top). Esclude NaN automaticamente.
display(dforder_items.describe(include='all'))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89316 entries, 0 to 89315
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          89316 non-null  object
 1   product_id        89316 non-null  object
 2   seller_id         89316 non-null  object
 3   price             89316 non-null  float64
 4   shipping_charges  89316 non-null  float64
dtypes: float64(2), object(3)
memory usage: 3.4+ MB

None

              price  shipping_charges
count  89316.000000      89316.000000
mean     340.900543         44.283210
std      557.459897         37.672491
min        0.850000          0.000000
25%       59.650000         20.110000
50%      136.900000         35.055000
75%      399.200000         57.190000
max     6735.000000        409.680000

,order_id,product_id,seller_id,price,shipping_charges
count,89316,89316,89316,89316.000000,89316.000000
unique,89316,27451,2929,NaN,NaN
top,Axfy13Hk4PIk,0vbEvli2JYJu,RKad98cTxhSb,NaN,NaN
freq,1,405,1657,NaN,NaN
mean,NaN,NaN,NaN,340.900543,44.283210
std,NaN,NaN,NaN,557.459897,37.672491
min,NaN,NaN,NaN,0.850000,0.000000
25%,NaN,NaN,NaN,59.650000,20.110000
50%,NaN,NaN,NaN,136.900000,35.055000
75%,NaN,NaN,NaN,399.200000,57.190000
max,NaN,NaN,NaN,6735.000000,409.680000

#### 5. Il dataframe PAYMENTS in analisi ha 89316 righe e 5 colonne.

Dall'analisi descrittiva nessuna colonna contiene valori nulli.

Senza valori duplicati.

Le colonne del dataframe Payments nel dettaglio:
- **order_id**: è un oggetto che contiene l'ID dell'ordine
- **payment_sequential**: è un intero che contiene il pagamento sequenziale
- **payment_type**: è un oggetto che contiene il tipo di pagamento
- **payment_installments**: è un intero che contiene rate di pagamento
- **payment_value**: è un float che contiene il valore del pagamento

Colonne richieste per la tabella `payments`
- `payment_id` (PK)
- `order_id` (FK → `orders.order_id`)
- `payment_sequential`
- `payment_type`
- `payment_installments`
- `payment_value`

#### Dopo il controllo:
- Trasformato la tabella in base alle entità e agli attributi richiesti con totale 89316 righe e 6 colonne.

In [64]:
# Import dataset or dataframe / Importo set di dati o dataframe 
dfpayments = pd.read_csv('df_Payments.csv', low_memory=False)

# Mostrare i nomi delle colonne e i tipi di dati all'interno e se questi dati hanno dei dati mancati
display(dfpayments.info())
# Genere un riepilogo statistico automatico delle colonne numeriche - Restituisce una tabella con metriche chiave: count (numero valori non-null), mean (media), std (deviazione standard), min (minimo), 25% (1° quartile), 50% (mediana), 75% (3° quartile), max (massimo), evidenziando distribuzioni, outlier e tendenze
display(dfpayments.describe())
# Genere statistiche descrittive per tutte le colonne del DataFrame, inclusi tipi numerici, categorici (object/string), booleani e datetime, anziché solo numeriche. Per colonne numeriche mostra count, mean, std, min, quartili (25%, 50%/mediana, 75%), max; per categoriche aggiunge unique (valori unici), top (valore più frequente), freq (frequenza top). Esclude NaN automaticamente.
display(dfpayments.describe(include='all'))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89316 entries, 0 to 89315
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   order_id              89316 non-null  object
 1   payment_sequential    89316 non-null  int64
 2   payment_type          89316 non-null  object
 3   payment_installments  89316 non-null  int64
 4   payment_value         89316 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 3.4+ MB

None

       payment_sequential  payment_installments  payment_value
count        89316.000000          89316.000000   89316.000000
mean             1.099646              2.965717     268.657190
std              0.772658              2.796406     344.409566
min              1.000000              0.000000       0.000000
25%              1.000000              1.000000      84.340000
50%              1.000000              2.000000     171.860000
75%              1.000000              4.000000     313.530000
max             29.000000             24.000000    7274.880000

,order_id,payment_sequential,payment_type,payment_installments,payment_value
count,89316,89316.000000,89316,89316.000000,89316.000000
unique,89316,NaN,4,NaN,NaN
top,Axfy13Hk4PIk,NaN,credit_card,NaN,NaN
freq,1,NaN,65814,NaN,NaN
mean,NaN,1.099646,NaN,2.965717,268.657190
std,NaN,0.772658,NaN,2.796406,344.409566
min,NaN,1.000000,NaN,0.000000,0.000000
25%,NaN,1.000000,NaN,1.000000,84.340000
50%,NaN,1.000000,NaN,2.000000,171.860000
75%,NaN,1.000000,NaN,4.000000,313.530000
max,NaN,29.000000,NaN,24.000000,7274.880000

### Valori mancanti (Missing Values) e Duplicati

#### Dati Mancanti isnull()

- Dati mancanti del dataframe CUSTOMERS

In [65]:
# Check for null values and sum them up for each column / Controllo i valori nulli e sommali per ogni colonna
null_values_count = dfcustomers.isnull().sum()

# Filter to show only columns that have null values ​​and create a variable that contains all the data for the null column
# Filtro per mostrare solo le colonne che hanno valori nulli e creo una variabile che contiene tutti i dati per colonna null
columns_with_null = null_values_count[null_values_count > 0].sort_values(ascending=False)

if not columns_with_null.empty:
    print("Colonne con valori nulli e il loro conteggio:")
    print(columns_with_null)
else:
    print("Nessuna colonna contiene valori nulli.")

Nessuna colonna contiene valori nulli.

- Dati mancanti del dataframe PRODUCTS

In [66]:
# Check for null values and sum them up for each column / Controllo i valori nulli e sommali per ogni colonna
null_values_count = dfproducts.isnull().sum()

# Filter to show only columns that have null values ​​and create a variable that contains all the data for the null column
# Filtro per mostrare solo le colonne che hanno valori nulli e creo una variabile che contiene tutti i dati per colonna null
columns_with_null = null_values_count[null_values_count > 0].sort_values(ascending=False)

if not columns_with_null.empty:
    print("Colonne con valori nulli e il loro conteggio:")
    print(columns_with_null)
else:
    print("Nessuna colonna contiene valori nulli.")

Colonne con valori nulli e il loro conteggio:
product_category_name    308
product_weight_g          15
product_length_cm         15
product_height_cm         15
product_width_cm          15
dtype: int64

In [67]:
# CREO DATAFRAME pd.DataFrame
# Controllo tutti i dati null per colonna e seleziono solo quelli che hanno un valore superiore a 0 e li ordino in modo decrescente
# Dividendola per la lunghezza delle righe del dataframe e moltiplicandola per 100 
# round -> funzione che arrotonda all'intero più vicino
dfproducts_missing = pd.DataFrame(
    #creazione delle colonne NomeColonna : ValoridaAssegnare
    {
        'Colonna': dfproducts.columns,
        'N_Dati_Mancanti':(dfproducts.isnull().sum()).round(2),
        '%_Dati_Mancanti': (dfproducts.isnull().sum()/len(dfproducts)*100).round(3),
    }
    #query per pulire il nuovo DataFrame e ordinare (sort_values) i valori
).query('N_Dati_Mancanti>0').sort_values('N_Dati_Mancanti',ascending=False)

display(dfproducts_missing)

                                     Colonna  N_Dati_Mancanti  %_Dati_Mancanti
product_category_name  product_category_name              308            0.345
product_weight_g            product_weight_g               15            0.017
product_length_cm          product_length_cm               15            0.017
product_height_cm          product_height_cm               15            0.017
product_width_cm            product_width_cm               15            0.017

- Dati mancanti del dataframe ORDERS

In [68]:
# Check for null values and sum them up for each column / Controllo i valori nulli e sommali per ogni colonna
null_values_count = dforders.isnull().sum()

# Filter to show only columns that have null values ​​and create a variable that contains all the data for the null column
# Filtro per mostrare solo le colonne che hanno valori nulli e creo una variabile che contiene tutti i dati per colonna null
columns_with_null = null_values_count[null_values_count > 0].sort_values(ascending=False)

if not columns_with_null.empty:
    print("Colonne con valori nulli e il loro conteggio:")
    print(columns_with_null)
else:
    print("Nessuna colonna contiene valori nulli.")

Colonne con valori nulli e il loro conteggio:
order_delivered_timestamp    1889
order_approved_at               9
dtype: int64

In [69]:
# CREO DATAFRAME pd.DataFrame
# Controllo tutti i dati null per colonna e seleziono solo quelli che hanno un valore superiore a 0 e li ordino in modo decrescente
# Dividendola per la lunghezza delle righe del dataframe e moltiplicandola per 100 
# round -> funzione che arrotonda all'intero più vicino
dforders_missing = pd.DataFrame(
    #creazione delle colonne NomeColonna : ValoridaAssegnare
    {
        'Colonna': dforders.columns,
        'N_Dati_Mancanti':(dforders.isnull().sum()).round(2),
        '%_Dati_Mancanti': (dforders.isnull().sum()/len(dfproducts)*100).round(3),
    }
    #query per pulire il nuovo DataFrame e ordinare (sort_values) i valori
).query('N_Dati_Mancanti>0').sort_values('N_Dati_Mancanti',ascending=False)

display(dforders_missing)

,Colonna,N_Dati_Mancanti,%_Dati_Mancanti
order_delivered_timestamp,order_delivered_timestamp,1889,2.115
order_approved_at,order_approved_at,9,0.010

- Dati mancanti del dataframe ORDER ITEMS

In [70]:
# Check for null values and sum them up for each column / Controllo i valori nulli e sommali per ogni colonna
null_values_count = dforder_items.isnull().sum()

# Filter to show only columns that have null values ​​and create a variable that contains all the data for the null column
# Filtro per mostrare solo le colonne che hanno valori nulli e creo una variabile che contiene tutti i dati per colonna null
columns_with_null = null_values_count[null_values_count > 0].sort_values(ascending=False)

if not columns_with_null.empty:
    print("Colonne con valori nulli e il loro conteggio:")
    print(columns_with_null)
else:
    print("Nessuna colonna contiene valori nulli.")

Nessuna colonna contiene valori nulli.

- Dati mancanti del dataframe PAYMENTS

In [71]:
# Check for null values and sum them up for each column / Controllo i valori nulli e sommali per ogni colonna
null_values_count = dfpayments.isnull().sum()

# Filter to show only columns that have null values ​​and create a variable that contains all the data for the null column
# Filtro per mostrare solo le colonne che hanno valori nulli e creo una variabile che contiene tutti i dati per colonna null
columns_with_null = null_values_count[null_values_count > 0].sort_values(ascending=False)

if not columns_with_null.empty:
    print("Colonne con valori nulli e il loro conteggio:")
    print(columns_with_null)
else:
    print("Nessuna colonna contiene valori nulli.")

Nessuna colonna contiene valori nulli.

#### Dati Duplicati (duplicated())

In [72]:
# Valori duplicati per tutto il dataFrame
dfcustomers.duplicated().sum()
# Valori duplicati per le colonne asin e review_id del DataFrame
dfcustomers[dfcustomers.duplicated(subset=['customer_id'], keep='first')]

Empty DataFrame
Columns: [customer_id, customer_zip_code_prefix, customer_city, customer_state]
Index: []

In [74]:
# Valori duplicati per tutto il dataFrame
dfproducts.duplicated().sum()
# Valori duplicati per le colonne asin e review_id del DataFrame
dfproducts[dfproducts.duplicated(subset=['product_id'], keep='first')]

,product_id,product_category_name,product_weight_g,product_length_cm,product_height_cm,product_width_cm
55,DXG0TFaZjGHO,toys,200.0,16.0,7.0,11.0
168,G16XPtJuiBOe,toys,150.0,16.0,4.0,13.0
186,SLTlrWtcYt1m,toys,1750.0,37.0,22.0,40.0
187,GvBzGCvvIC2D,toys,1000.0,53.0,8.0,18.0
253,8EMcxO7AFhVP,toys,180.0,17.0,10.0,13.0
...,...,...,...,...,...,...
89309,HMryprA6nfPG,bed_bath_table,1650.0,46.0,3.0,34.0
89310,K1LKw6GfKN4j,toys,500.0,16.0,21.0,18.0
89312,KXSbyJWtMMwZ,toys,600.0,16.0,16.0,16.0
89313,EG4wDSpFyTth,health_beauty,250.0,22.0,10.0,18.0
89314,ZWyg4uNWPHjJ,toys,250.0,16.0,2.0,11.0

In [75]:
# CREO DATAFRAME pd.DataFrame
# Controllo tutti i dati null per colonna e seleziono solo quelli che hanno un valore superiore a 0 e li ordino in modo decrescente
# Dividendola per la lunghezza delle righe del dataframe e moltiplicandola per 100 
# round -> funzione che arrotonda all'intero più vicino
dfproducts_duplicate = pd.DataFrame(
    #creazione delle colonne NomeColonna : ValoridaAssegnare
    {
        'Colonna': dfproducts.columns,
        'N_Dati_Duplicati':(dfproducts.duplicated().sum()).round(2),
        '%_Dati_Duplicati': (dfproducts.duplicated().sum()/len(dfproducts)*100).round(3),
    }
    #query per pulire il nuovo DataFrame e ordinare (sort_values) i valori
).query('N_Dati_Duplicati>0').sort_values('N_Dati_Duplicati',ascending=False)

display(dfproducts_duplicate)

                 Colonna  N_Dati_Duplicati  %_Dati_Duplicati
0             product_id             61865            69.265
1  product_category_name             61865            69.265
2       product_weight_g             61865            69.265
3      product_length_cm             61865            69.265
4      product_height_cm             61865            69.265
5       product_width_cm             61865            69.265

In [76]:
# Valori duplicati per tutto il dataFrame
dforders.duplicated().sum()
# Valori duplicati per le colonne asin e review_id del DataFrame
dforders[dforders.duplicated(subset=['order_id'], keep='first')]

Empty DataFrame
Columns: [order_id, customer_id, order_status, order_purchase_timestamp, order_approved_at, order_delivered_timestamp, order_estimated_delivery_date]
Index: []

In [77]:
# Valori duplicati per tutto il dataFrame
dforder_items.duplicated().sum()
# Valori duplicati per le colonne asin e review_id del DataFrame
dforder_items[dforder_items.duplicated(subset=['order_id'], keep='first')]

Empty DataFrame
Columns: [order_id, product_id, seller_id, price, shipping_charges]
Index: []

In [78]:
# Valori duplicati per tutto il dataFrame
dfpayments.duplicated().sum()
# Valori duplicati per le colonne asin e review_id del DataFrame
dfpayments[dfpayments.duplicated(subset=['order_id'], keep='first')]

Empty DataFrame
Columns: [order_id, payment_sequential, payment_type, payment_installments, payment_value]
Index: []

#### Cancellazione dati Mancanti e Duplicati e Conversione coretta dei tipi dei dati

In [79]:
# Creo copia del dataframe products
dfproductscopy = dfproducts.copy()
display(dfproductscopy.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89316 entries, 0 to 89315
Data columns (total 6 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   product_id             89316 non-null  object
 1   product_category_name  89008 non-null  object
 2   product_weight_g       89301 non-null  float64
 3   product_length_cm      89301 non-null  float64
 4   product_height_cm      89301 non-null  float64
 5   product_width_cm       89301 non-null  float64
dtypes: float64(4), object(2)
memory usage: 4.1+ MB

None

In [80]:
# Cancello le celle con i valori mancanti per collana
dfproductscopy.dropna(inplace = True)
display(dfproductscopy.info())

<class 'pandas.core.frame.DataFrame'>
Index: 88993 entries, 0 to 89315
Data columns (total 6 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   product_id             88993 non-null  object
 1   product_category_name  88993 non-null  object
 2   product_weight_g       88993 non-null  float64
 3   product_length_cm      88993 non-null  float64
 4   product_height_cm      88993 non-null  float64
 5   product_width_cm       88993 non-null  float64
dtypes: float64(4), object(2)
memory usage: 4.8+ MB

None

In [81]:
# Cancello tutti i dati duplicati per colonna
dfproductscopy.drop_duplicates(inplace = True)
display(dfproductscopy.info())

# Creo nuovo CSV file
dfproductscopy.to_csv('dfproductscopy.csv', index=False)
print("\nFile 'dfproductscopy.csv' creato con successo!")

<class 'pandas.core.frame.DataFrame'>
Index: 27308 entries, 0 to 89315
Data columns (total 6 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   product_id             27308 non-null  object
 1   product_category_name  27308 non-null  object
 2   product_weight_g       27308 non-null  float64
 3   product_length_cm      27308 non-null  float64
 4   product_height_cm      27308 non-null  float64
 5   product_width_cm       27308 non-null  float64
dtypes: float64(4), object(2)
memory usage: 1.5+ MB

None

File 'dfproductscopy.csv' creato con successo!

In [82]:
# Creo copia del dataframe orders
dforderscopy = dforders.copy()
display(dforderscopy.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89316 entries, 0 to 89315
Data columns (total 7 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       89316 non-null  object
 1   customer_id                    89316 non-null  object
 2   order_status                   89316 non-null  object
 3   order_purchase_timestamp       89316 non-null  object
 4   order_approved_at              89307 non-null  object
 5   order_delivered_timestamp      87427 non-null  object
 6   order_estimated_delivery_date  89316 non-null  object
dtypes: object(7)
memory usage: 4.8+ MB

None

In [83]:
# Sostituisco i valori nulli con DEFAULT_DATETIME
# Colonne con valori nulli e il loro conteggio:
# order_delivered_timestamp    1889
# order_approved_at               9

# Load CSV / Carica CSV
dforderscopy = pd.read_csv("df_Orders.csv")

# Define default placeholder datetime / Definisco il segnaposto data/ora predefinito
DEFAULT_DATETIME = pd.Timestamp("1970-01-01 00:00:00")

# Replace empty / missing values in datetime columns / Sostituisco i valori vuoti/mancanti nelle colonne datetime
dforderscopy["order_delivered_timestamp"] = (
    pd.to_datetime(dforderscopy["order_delivered_timestamp"], errors="coerce")
    .fillna(DEFAULT_DATETIME)
)

dforderscopy["order_approved_at"] = (
    pd.to_datetime(dforderscopy["order_approved_at"], errors="coerce")
    .fillna(DEFAULT_DATETIME)
)

# Conversione coretta dei tipi dei dati
dforderscopy['order_purchase_timestamp'] = pd.to_datetime(dforderscopy['order_purchase_timestamp'])
dforderscopy['order_estimated_delivery_date'] = pd.to_datetime(dforderscopy['order_estimated_delivery_date'])

display(dforderscopy.info())

# Creo nuovo CSV file
dforderscopy.to_csv('dforderscopy.csv', index=False)
print("\nFile 'dforderscopy.csv' creato con successo!")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89316 entries, 0 to 89315
Data columns (total 7 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       89316 non-null  object
 1   customer_id                    89316 non-null  object
 2   order_status                   89316 non-null  object
 3   order_purchase_timestamp       89316 non-null  datetime64[ns]
 4   order_approved_at              89316 non-null  datetime64[ns]
 5   order_delivered_timestamp      89316 non-null  datetime64[ns]
 6   order_estimated_delivery_date  89316 non-null  datetime64[ns]
dtypes: datetime64[ns](4), object(3)
memory usage: 4.8+ MB

None

File 'dforderscopy.csv' creato con successo!

### Trasformazione delle tabelle in base alle entità e agli attributi richiesti

Tabella `customers`
- `customer_id` (PK)
- `customer_zip_code`
- `customer_city`
- `customer_state`
- `customer_country`

In [84]:
# Load CSV / Carica CSV
dfcustomers = pd.read_csv('df_Customers.csv', low_memory=False)

# Rinomino colonna product_category_name
dfcustomers = dfcustomers.rename(
    columns={
        "customer_zip_code_prefix": "customer_zip_code"
    }
)

# Add new columns / Aggiungo nuove colonne
dfcustomers["customer_country"] = ""

# Reorder columns to match target schema / Riordina le colonne in base allo schema di destinazione
dfcustomers = dfcustomers[
    [
        "customer_id",
        "customer_zip_code",
        "customer_city",
        "customer_state",
        "customer_country",
    ]
]

# Save transformed CSV / Salva CSV trasformato
dfcustomers.to_csv("df_Customers_NEW.csv", index=False)
display(dfcustomers.info())
print("\nFile 'df_Customers_NEW.csv' creato con successo!")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89316 entries, 0 to 89315
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        89316 non-null  object
 1   customer_zip_code  89316 non-null  int64
 2   customer_city      89316 non-null  object
 3   customer_state     89316 non-null  object
 4   customer_country   89316 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.4+ MB

None

File 'df_Customers_NEW.csv' creato con successo!

Tabella `products`
- `product_id` (PK)
- `product_category`
- `product_weight_g`
- `product_length_cm`
- `product_height_cm`
- `product_width_cm`

In [85]:
# Load CSV / Carica CSV
dfproductscopy = pd.read_csv("dfproductscopy.csv")

# Rinomino colonna product_category_name
dfproductscopy = dfproductscopy.rename(
    columns={
        "product_category_name": "product_category"
    }
)

# Reorder columns to match target schema / Riordino le colonne in base allo schema di destinazione
dfproductscopy = dfproductscopy[
    [
        "product_id",
        "product_category",
        "product_weight_g",
        "product_length_cm",
        "product_height_cm",
        "product_width_cm"
    ]
]

# Save transformed CSV / Salva CSV trasformato
dfproductscopy.to_csv("dfproductscopy_NEW.csv", index=False)
display(dfproductscopy.info())
print("\nFile 'dfproductscopy_NEW.csv' creato con successo!")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27308 entries, 0 to 27307
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   product_id         27308 non-null  object
 1   product_category   27308 non-null  object
 2   product_weight_g   27308 non-null  float64
 3   product_length_cm  27308 non-null  float64
 4   product_height_cm  27308 non-null  float64
 5   product_width_cm   27308 non-null  float64
dtypes: float64(4), object(2)
memory usage: 1.3+ MB

None

File 'dfproductscopy_NEW.csv' creato con successo!

Tabella `orders`
- `order_id` (PK)
- `customer_id` (FK → `customers.customer_id`)
- `order_status`
- `order_date`
- `order_approved_at`
- `delivery_date`
- `estimated_delivery_date`
- `shipping_city`
- `shipping_state`

In [86]:
# Load CSV / Carica CSV
dforderscopy = pd.read_csv("dforderscopy.csv")

# Rinomino colonna product_category_name
dforderscopy = dforderscopy.rename(
    columns={
        "order_purchase_timestamp": "order_date",
        "order_delivered_timestamp": "delivery_date",
        "order_estimated_delivery_date": "estimated_delivery_date"
    }
)

# Add new columns / Aggiungo nuove colonne
dforderscopy["shipping_city"] = ""
dforderscopy["shipping_state"] = ""

# Conversione coretta dei tipi dei dati
dforderscopy['order_date'] = pd.to_datetime(dforderscopy['order_date'])
dforderscopy['order_approved_at'] = pd.to_datetime(dforderscopy['order_approved_at'])
dforderscopy['delivery_date'] = pd.to_datetime(dforderscopy['delivery_date'])
dforderscopy['estimated_delivery_date'] = pd.to_datetime(dforderscopy['estimated_delivery_date'])

# Save transformed CSV / Salva CSV trasformato
dforderscopy.to_csv("dforderscopy_transformed.csv", index=False)
display(dforderscopy.info())
print("\nFile 'dforderscopy_transformed.csv' creato con successo!")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89316 entries, 0 to 89315
Data columns (total 9 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   order_id                 89316 non-null  object
 1   customer_id              89316 non-null  object
 2   order_status             89316 non-null  object
 3   order_date               89316 non-null  datetime64[ns]
 4   order_approved_at        89316 non-null  datetime64[ns]
 5   delivery_date            89316 non-null  datetime64[ns]
 6   estimated_delivery_date  89316 non-null  datetime64[ns]
 7   shipping_city            89316 non-null  object
 8   shipping_state           89316 non-null  object
dtypes: datetime64[ns](4), object(5)
memory usage: 6.1+ MB

None

File 'dforderscopy_transformed.csv' creato con successo!

- Filter out rows where order_status is 'canceled' and remove

Tabella `order_items`
- `order_item_id` (PK)
- `order_id` (FK → `orders.order_id`)
- `product_id` (FK → `products.product_id`)
- `seller_id`
- `price`
- `shipping_charges`

In [87]:
# Load CSV / Carica CSV
dforder_items = pd.read_csv("df_OrderItems.csv")

# Add new columns / Aggiungo nuova colonna order_item_id (simulate PRIMARY KEY)
# Add order_item_id (simulate PRIMARY KEY)
dforder_items["order_item_id"] = range(1, len(dforder_items) + 1)
dforder_items["order_item_id"] = dforder_items["order_item_id"].astype("int64")

# Enforce PRIMARY KEY–like behavior (validation)
if dforder_items["order_item_id"].isnull().any():
    raise ValueError("order_item_id contains NULL values")

if not dforder_items["order_item_id"].is_unique:
    raise ValueError("order_item_id is not unique")

# Reorder columns to match target schema / Riordina le colonne in base allo schema di destinazione
dforder_items = dforder_items[
    [
        "order_item_id",
        "order_id",
        "product_id",
        "seller_id",
        "price",
        "shipping_charges"
    ]
]

# Save transformed CSV / Salva CSV trasformato
dforder_items.to_csv("dforder_items_transformed.csv", index=False)
display(dforder_items.info())
print("\nFile 'dforder_items_transformed.csv' creato con successo!")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89316 entries, 0 to 89315
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_item_id     89316 non-null  int64
 1   order_id          89316 non-null  object
 2   product_id        89316 non-null  object
 3   seller_id         89316 non-null  object
 4   price             89316 non-null  float64
 5   shipping_charges  89316 non-null  float64
dtypes: float64(2), int64(1), object(3)
memory usage: 4.1+ MB

None

File 'dforder_items_transformed.csv' creato con successo!

Tabella `payments`
- `payment_id` (PK)
- `order_id` (FK → `orders.order_id`)
- `payment_sequential`
- `payment_type`
- `payment_installments`
- `payment_value`

In [88]:
# Load CSV / Carica CSV
dfpayments = pd.read_csv('df_Payments.csv', low_memory=False)

# Add new columns / Aggiungo nuova colonna order_item_id (simulate PRIMARY KEY)
# Add order_item_id (simulate PRIMARY KEY)
dfpayments["payment_id"] = range(1, len(dforder_items) + 1)
dfpayments["payment_id"] = dfpayments["payment_id"].astype("int64")

# Enforce PRIMARY KEY–like behavior (validation)
if dfpayments["payment_id"].isnull().any():
    raise ValueError("payment_id contains NULL values")

if not dfpayments["payment_id"].is_unique:
    raise ValueError("payment_id is not unique")

# Reorder columns to match target schema / Riordino le colonne in base allo schema di destinazione
dfpayments = dfpayments[
    [
        "payment_id",
        "order_id",
        "payment_sequential",
        "payment_type",
        "payment_installments",
        "payment_value"
    ]
]

# Save transformed CSV / Salva CSV trasformato
dfpayments.to_csv("dfpayments_transformed.csv", index=False)
display(dfpayments.info())
print("\nFile 'dfpayments_transformed.csv' creato con successo!")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89316 entries, 0 to 89315
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   payment_id            89316 non-null  int64
 1   order_id              89316 non-null  object
 2   payment_sequential    89316 non-null  int64
 3   payment_type          89316 non-null  object
 4   payment_installments  89316 non-null  int64
 5   payment_value         89316 non-null  float64
dtypes: float64(1), int64(3), object(2)
memory usage: 4.1+ MB

None

File 'dfpayments_transformed.csv' creato con successo!